apiVersion: v1
kind: Namespace
metadata:
  name: min-versions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: min-versions
  name: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: min-versions:controller
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
    verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: min-versions:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: min-versions:controller
subjects:
  - kind: ServiceAccount
    namespace: min-versions
    name: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: min-versions
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: min-versions-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: min-versions-controller
    spec:
      serviceAccountName: controller
      containers:
        - name: operator
          image: nresare/min-versions-controller:v0.0.1
